package com.ssafy.lyricit.common.type;

public enum EventType {
	LOUNGE_MESSAGE,
	ROOM_CREATED, ROOM_UPDATED, ROOM_DELETED, ROOM_MESSAGE,
	MEMBER_IN, MEMBER_MESSAGE, MEMBER_OUT, MEMBER_READY,
	SCORE_UPDATED
}
