package com.ssafy.lyricit.common.type;

public enum EventType {
	ONLINE, OFFLINE, LOUNGE_MESSAGE,
	ROOM_CREATED, ROOM_UPDATED, ROOM_DELETED, ROOM_MESSAGE, LEADER_CHANGED,
	MEMBER_IN, MEMBER_MESSAGE, MEMBER_OUT, MEMBER_READY,
	GAME_STARTED, ROUND_STARTED, SCORE_UPDATED
}
