package com.ssafy.lyricit.common.type;

public enum EventType {
	ONLINE, OFFLINE, LOUNGE_MESSAGE,
	ROOM_CREATED, ROOM_UPDATED, ROOM_DELETED, ROOM_MESSAGE, LEADER_CHANGED,
	MEMBER_IN, MEMBER_MESSAGE, MEMBER_OUT, MEMBER_READY,
	GAME_STARTED, GAME_ENDED, ROUND_STARTED, ROUND_ENDED, GAME_MESSAGE,
	HIGHLIGHT, HIGHLIGHT_TITLE, HIGHLIGHT_ARTIST, HIGHLIGHT_CANCELLED, CORRECT_ANSWER, INCORRECT_ANSWER
}
